### ISSUE TITLE
Roxygen help files won't use markdown formatting

### ISSUE THREAD

**Issue by esaschenck** [margotdv04/socialsciencer#6]
Hey @rudeboybert we aren't able to use markdown in roxygen help files.

Our description file contains the line:
```
Roxygen: list(markdown=TRUE)
```
However, when we use `` tick marks in the help files, they display as apostrophes: 'country_indicators' instead of `country_indicators`

**Comment by esaschenck** [comment]
Turns out we needed spaces between the equals sign!

This code works:
```
Roxygen: list(markdown = TRUE)
```

**Comment by rudeboybert** [comment]
Great!
